name: Testing Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout To Project
        uses: actions/checkout@v3
      - name: Installing NodeJs
        uses: actions/setup-node@v3
        with:
          node-module: 18
      - name: Installing Dependencies
        run: npm ci
      - name: Running Test 
        run: npm test
      - name: Running Linting
        run: npm run lint
      - name: Deploy
        run: echo "Deploying"